// Plan-tier resource limits.
// Consumed by lib/services/LimitService — never referenced directly in routes.
// Infinity = unlimited for that tier.
export const PLAN_LIMITS = Object.freeze({
  STARTER: {
    maxBarbers:            3,
    maxServices:           20,
    maxBranches:           1,
    maxMonthlyAppointments: 300,
    maxStorageGB:          2,
    maxApiRequestsPerDay:  0,     // API_ACCESS feature required
    maxMonthlyAiMessages:  0,
    maxMonthlyVoiceMinutes: 0,
    maxMonthlyWhatsAppMessages: 0,
  },
  PRO: {                          // legacy tier — treated as PROFESSIONAL
    maxBarbers:            Infinity,
    maxServices:           Infinity,
    maxBranches:           3,
    maxMonthlyAppointments: Infinity,
    maxStorageGB:          20,
    maxApiRequestsPerDay:  10_000,
    maxMonthlyAiMessages:  0,
    maxMonthlyVoiceMinutes: 0,
    maxMonthlyWhatsAppMessages: 0,
  },
  ENTERPRISE: {
    maxBarbers:            Infinity,
    maxServices:           Infinity,
    maxBranches:           Infinity,
    maxMonthlyAppointments: Infinity,
    maxStorageGB:          Infinity,
    maxApiRequestsPerDay:  Infinity,
    maxMonthlyAiMessages:  Infinity,
    maxMonthlyVoiceMinutes: Infinity,
    maxMonthlyWhatsAppMessages: Infinity,
  },
  PROFESSIONAL: {
    maxBarbers:            10,
    maxServices:           Infinity,
    maxBranches:           3,
    maxMonthlyAppointments: 2_000,
    maxStorageGB:          20,
    maxApiRequestsPerDay:  10_000,
    maxMonthlyAiMessages:  0,
    maxMonthlyVoiceMinutes: 0,
    maxMonthlyWhatsAppMessages: 0,
  },
  AI: {
    maxBarbers:            Infinity,
    maxServices:           Infinity,
    maxBranches:           10,
    maxMonthlyAppointments: Infinity,
    maxStorageGB:          100,
    maxApiRequestsPerDay:  100_000,
    maxMonthlyAiMessages:  10_000,
    maxMonthlyVoiceMinutes: 500,
    maxMonthlyWhatsAppMessages: 5_000,
  },
});

export const JOB_TYPES = Object.freeze({
  BIRTHDAY_CHECK:     "BIRTHDAY_CHECK",
  REVIEW_REMINDER:    "REVIEW_REMINDER",
  APPT_REMINDER:      "APPT_REMINDER",
  ANALYTICS_REFRESH:  "ANALYTICS_REFRESH",
  GOOGLE_SYNC:        "GOOGLE_SYNC",
  CLEANUP:            "CLEANUP",
  CACHE_REFRESH:      "CACHE_REFRESH",
  WEBHOOK_RETRY:      "WEBHOOK_RETRY",
  AI_TASK:            "AI_TASK",
  EXPORT:             "EXPORT",
});

export const INTEGRATION_PROVIDER = Object.freeze({
  GOOGLE_BUSINESS:  "GOOGLE_BUSINESS",
  GOOGLE_CALENDAR:  "GOOGLE_CALENDAR",
  GOOGLE_REVIEWS:   "GOOGLE_REVIEWS",
  META:             "META",
  WHATSAPP:         "WHATSAPP",
  INSTAGRAM:        "INSTAGRAM",
  OPENAI:           "OPENAI",
  CLAUDE:           "CLAUDE",
  GEMINI:           "GEMINI",
  TWILIO:           "TWILIO",
  FIREBASE:         "FIREBASE",
  STRIPE:           "STRIPE",
  IYZICO:           "IYZICO",
  ZAPIER:           "ZAPIER",
  MAKE:             "MAKE",
  N8N:              "N8N",
});
